[project]
name = "mem0-extract-titles"
version = "0.1.0"
description = "Servidor MCP para extraer títulos y subtítulos de texto"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "mem0ai>=0.1.88",
    "vecs>=0.4.5"
]
