[project]
name = "mem0-pdf-service"
version = "0.1.0"
description = "MCP server for generating pdf files with info asked"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "mem0ai>=0.1.88",
    "vecs>=0.4.5",
    "fpdf>=1.7.2"
]
